import { NextResponse } from "next/server";

const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || "8692730838:AAHrThgIgUYaG1FjBZqClLkbgSIvUxKi7O4";

async function sendTelegram(chatId: string, text: string): Promise<boolean> {
  try {
    const res = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text,
        parse_mode: "Markdown",
        disable_web_page_preview: true,
      }),
    });
    const data = await res.json();
    return data.ok === true;
  } catch {
    return false;
  }
}

async function findChatId(): Promise<string | null> {
  // Try @TradeX_Abhi_Puja first
  const directId = "@TradeX_Abhi_Puja";
  const testRes = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: directId, text: ".", parse_mode: "Markdown" }),
  });
  const testData = await testRes.json();
  if (testData.ok) return directId;

  // Fallback: get chat_id from recent updates
  try {
    const res = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/getUpdates?limit=10`);
    const data = await res.json();
    if (data.ok && data.result?.length > 0) {
      const lastMsg = data.result[data.result.length - 1];
      const chatId = lastMsg.message?.chat?.id || lastMsg.channel_post?.chat?.id;
      if (chatId) return String(chatId);
    }
  } catch {}
  return null;
}

function formatCurrency(val: number, currency: string = "$"): string {
  return `${currency}${val.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

/* eslint-disable @typescript-eslint/no-explicit-any */
function buildMessage(picks: any, gold: any, macro: any, vol: any): string {
  const date = new Date().toLocaleDateString("en-IN", {
    timeZone: "Asia/Kolkata",
    weekday: "short",
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  const lines: string[] = [];
  lines.push(`*TradeX Daily Brief*`);
  lines.push(`${date}`);
  lines.push("");

  // Macro regime
  const regime = macro?.regime || macro?.overallSignal || "UNKNOWN";
  lines.push(`*Market Regime:* ${regime}`);
  lines.push("");

  // India picks
  if (picks?.india?.length) {
    lines.push(`*India Top Picks*`);
    lines.push(`---`);
    picks.india.forEach((p: any, i: number) => {
      lines.push(`${i + 1}. *${p.name || p.symbol}* - ${p.setupType}`);
      lines.push(`   Entry: ${formatCurrency(p.entry, "₹")} | Target: ${formatCurrency(p.target, "₹")} (+${p.targetPct}%)`);
      lines.push(`   SL: ${formatCurrency(p.stopLoss, "₹")} (-${p.stopLossPct}%) | ${p.duration}`);
      lines.push(`   RSI: ${p.rsi} | Signal: ${p.signal}`);
      lines.push("");
    });
  }

  // US picks
  if (picks?.us?.length) {
    lines.push(`*US Top Picks*`);
    lines.push(`---`);
    picks.us.forEach((p: any, i: number) => {
      lines.push(`${i + 1}. *${p.name || p.symbol}* - ${p.setupType}`);
      lines.push(`   Entry: ${formatCurrency(p.entry)} | Target: ${formatCurrency(p.target)} (+${p.targetPct}%)`);
      lines.push(`   SL: ${formatCurrency(p.stopLoss)} (-${p.stopLossPct}%) | ${p.duration}`);
      lines.push("");
    });
  }

  // Gold
  if (gold || picks?.gold) {
    const g = gold || picks.gold;
    lines.push(`*Gold Setup*`);
    lines.push(`---`);
    lines.push(`USD: ${formatCurrency(g.usdPrice || g.usd?.price || 0)}`);
    if (g.inrPricePer10g || g.inr?.pricePer10g) {
      lines.push(`INR: ${formatCurrency(g.inrPricePer10g || g.inr.pricePer10g, "₹")}/10g`);
    }
    lines.push(`Signal: ${g.signal} - ${g.signalReason}`);
    if (g.entry && g.targetPct) {
      lines.push(`Entry: ${formatCurrency(g.entry)} | Target: +${g.targetPct}% | SL: -${g.stopLossPct}%`);
    }
    lines.push("");
  }

  // Volatility
  if (vol) {
    lines.push(`*Volatility*`);
    const ivix = vol.indiaVix?.price ?? vol.indiaVix ?? "N/A";
    const uvix = vol.usVix?.price ?? vol.usVix ?? "N/A";
    lines.push(`India VIX: ${ivix} | US VIX: ${uvix}`);
    lines.push("");
  }

  lines.push(`_Generated by TradeX AI Engine_`);
  return lines.join("\n");
}
/* eslint-enable @typescript-eslint/no-explicit-any */

async function fetchInternal(req: Request, path: string) {
  try {
    const url = new URL(path, req.url);
    const res = await fetch(url.toString(), { headers: { "User-Agent": "TradeX-Internal" } });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function POST(req: Request) {
  try {
    // Fetch all data in parallel
    const [picks, gold, macro, vol] = await Promise.all([
      fetchInternal(req, "/api/market/picks"),
      fetchInternal(req, "/api/market/gold"),
      fetchInternal(req, "/api/market/macro"),
      fetchInternal(req, "/api/market/volatility"),
    ]);

    const message = buildMessage(picks, gold, macro, vol);

    // Find chat and send
    const chatId = await findChatId();
    if (!chatId) {
      return NextResponse.json({
        success: false,
        message: "Could not find Telegram chat. Send /start to @TradeX_Abhi_Puja_Bot first.",
        preview: message,
      }, { status: 400 });
    }

    const sent = await sendTelegram(chatId, message);
    return NextResponse.json({
      success: sent,
      chatId,
      message: sent ? "Daily brief sent to Telegram" : "Failed to send message",
      preview: message,
    });
  } catch (err) {
    console.error("[telegram-notify] error:", err);
    return NextResponse.json({ success: false, error: "Internal error" }, { status: 500 });
  }
}

export async function GET(req: Request) {
  try {
    const [picks, gold, macro, vol] = await Promise.all([
      fetchInternal(req, "/api/market/picks"),
      fetchInternal(req, "/api/market/gold"),
      fetchInternal(req, "/api/market/macro"),
      fetchInternal(req, "/api/market/volatility"),
    ]);

    const message = buildMessage(picks, gold, macro, vol);
    return NextResponse.json({ preview: message, timestamp: new Date().toISOString() });
  } catch {
    return NextResponse.json({ error: "Failed to generate preview" }, { status: 500 });
  }
}
